### ISSUE TITLE
在主题切换事件中少了个self

### ISSUE THREAD

**Issue by DemoJj** [fudax/vue-mindeditor#1]
#src\components\main_editor\navigator.vue
old:
minder.on("themechange", function(e) {
      pathHandler = self.getPathHandler(e.theme);
});
new:
minder.on("themechange", function(e) {
      self.pathHandler = self.getPathHandler(e.theme);
});

**Comment by fudax** [comment]
可是主题切换已经被我删除了啊，这段代码稍后删除
