### ISSUE TITLE
您参考的原项目如何启动可以告诉我吗

### ISSUE THREAD

**Issue by ShirlyZhang** [fudax/vue-mindeditor#10]
https://github.com/LingRay/mindmap 启动了是404 经查不是端口号冲突导致的 修改了也还是404

**Comment by fudax** [comment]
人家说明写的很清楚了啊，npm run dev~
如果单纯想用原来那位大神的代码，可以直接复制代码到我的工程下面覆盖文件之后启动，他那个webpack和vue版本太老了
