### ISSUE TITLE
大神求助

### ISSUE THREAD

**Issue by Hellcj** [fudax/vue-mindeditor#11]
大神能否添加mind备注和搜索功能哇，拜托拜托了，前端小渣拜读大神代码，只觉得转化的很棒但还是模仿不来o(╥﹏╥)o

**Comment by liangjingdev** [comment]
> 大神能否添加mind备注和搜索功能哇，拜托拜托了，前端小渣拜读大神代码，只觉得转化的很棒但还是模仿不来o(╥﹏╥)o

搞定了吗

**Comment by fudax** [comment]
代码基本是照抄这位大哥的，你们自己看下：https://github.com/LingRay/mindmap
