### ISSUE TITLE
为什么 npm run dev 打开的不是 localhost ？

### ISSUE THREAD

**Issue by sws797** [fudax/vue-mindeditor#15]
![image](https://user-images.githubusercontent.com/33458935/104984239-4f087980-5a49-11eb-9b7a-c229c2d99622.png)
`监听端口为 http://2408:8452:677:e打码打码3a6:3526:9cce:8088`
是一个大概这样的链接，我不懂webpack，实在搜不到为什么会出现这个问题

手动打开`localhost:8088`是可以的，但是我想知道为什么会出现这样的情况

**Comment by fudax** [comment]
你但凡用IDE搜一下localhost也就明白了，这种问题也需要开issue来解决吗？

![image](https://user-images.githubusercontent.com/2324608/105163146-7dbc4800-5b4e-11eb-8d6c-532b53ca54f1.png)

**Comment by sws797** [comment]
> 你但凡用IDE搜一下localhost也就明白了，这种问题也需要开issue来解决吗？
> 
> ![image](https://user-images.githubusercontent.com/2324608/105163146-7dbc4800-5b4e-11eb-8d6c-532b53ca54f1.png)

@fudax 谢谢指点，我真的不懂webpack，上网搜了很久也没搜到，完全没有往您说的这方面想。
如果不是您回复了我这个问题真的不知道要多久才能想到这边来

写代码真的是这样，不懂的撞破头都不懂，懂的可能两句话就解决了，感谢您的指点！
如果以后还碰到我这样的小白还请您多包含包含orz
